---
- hosts: all
  user: "{{ vm_user }}"
  become: yes
  become_method: sudo
  vars_files:
  - vars/vars.yml
  roles:
    - provision
    - nagios-core
    - nagios-plugins
    - nrpe
    - configure-nagios